----QUERY TO DISPLAY CUSTOMER LIST BY THE FIRST_NAME IN DESCENDING ORDER--------

SELECT FIRST_NAME 
FROM SALES.CUSTOMERS
ORDER BY FIRST_NAME DESC

-----QUESTION 2---------

SELECT FIRST_NAME, LAST_NAME, CITY
FROM SALES.CUSTOMERS
ORDER BY CITY  ASC,FIRST_NAME ASC

------QUESTION 3----------

SELECT TOP(3) PRODUCT_ID, PRODUCT_NAME, LIST_PRICE AS 'EXPENSIVE PRODUCTS'
FROM PRODUCTION.PRODUCTS
ORDER BY LIST_PRICE DESC

------QUESTION 4---------

SELECT PRODUCT_ID, PRODUCT_NAME, LIST_PRICE, MODEL_YEAR
FROM PRODUCTION.PRODUCTS
WHERE (LIST_PRICE) > 300 AND MODEL_YEAR = 2018

-----QUESTION 5----------

SELECT PRODUCT_ID, PRODUCT_NAME, LIST_PRICE, MODEL_YEAR
FROM PRODUCTION.PRODUCTS
WHERE (LIST_PRICE) > 3000 OR MODEL_YEAR = 2018

------QUESTION 6----------

SELECT PRODUCT_ID, PRODUCT_NAME, LIST_PRICE
FROM PRODUCTION.PRODUCTS
WHERE LIST_PRICE BETWEEN 1899 AND 1999.99

------QUESTION 7 ---------

SELECT PRODUCT_ID, PRODUCT_NAME, LIST_PRICE
FROM PRODUCTION.PRODUCTS
WHERE LIST_PRICE  IN( 299.99, 466.99, 489.99)

------QUESTION 8----------

SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME
FROM SALES.CUSTOMERS
WHERE LAST_NAME LIKE '[A-C]%'

--------QUESTION 9------------

SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME
FROM SALES.CUSTOMERS
WHERE FIRST_NAME NOT LIKE 'A%'

-------QUESTION 10 -----------

SELECT COUNT(CUSTOMER_ID) AS 'NUMBER OF CUSTOMERS', STATE, CITY
FROM SALES.CUSTOMERS
GROUP BY STATE, CITY

---------QUESTION 11-----------

SELECT COUNT(ORDER_ID) AS 'NUMBER OF ORDERS', CUSTOMER_ID, YEAR(ORDER_DATE) AS 'YEAR'
FROM SALES.ORDERS
GROUP BY CUSTOMER_ID, YEAR(ORDER_DATE)

--------QUESTION 12-----------

SELECT CATEGORY_ID, MAX(LIST_PRICE) AS 'MAX_LIST_PRICE', MIN(LIST_PRICE) AS 'MIN_LIST_PRICE'
FROM PRODUCTION.PRODUCTS
GROUP BY CATEGORY_ID
HAVING MAX(LIST_PRICE) > 4000 OR MIN(LIST_PRICE) < 500
